name: quaich
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - cython
  - snakemake
  - cooler
  - ucsc-bedgraphtobigwig
  - bioframe>=0.3.3
  - tqdm
  - toolz
